name: Build Workflow
on:
    
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: test
   

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
          
      - name: Hello from workflow
        run: |
          echo "Hello from the build area"
          
