name: Python CI in Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  python_project:
    runs-on: self-hosted
    container:
      image: python:3.11  # Use a Python container; you can replace with a custom image
    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python (if not already in the container)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      - name: Run tests
        run: |
          pytest

      # 5. Optional: Lint or format code
      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      # 6. Optional: Build or package project
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
