name: Python CI in Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  python_project:
    runs-on: self-hosted
    container:
      image: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Lint code
        run: |
          pip install flake8
          flake8 .
