name: Python Application

on:
#  push:
 #   branches:
  #    - main
      
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  python_project:
    if: ${{ github.event.inputs.environment == 'prod' }}
    runs-on: self-hosted
   

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
     

      - name: Verify installations
        run: |
         python3 --version
         pip3 --version
         make --version
         docker --version
        
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
          
      - name: Running Python Project
        run: |
          make setup
        # make testp
        #  make lint
        #  make coverage
   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Login to registry
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
         context: .
         push: true
         tags: madhhur168/myapp168:latest
       
