name: Python Application

on:
#  push:
 #   branches:
  #    - main
      
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  python_project:
    if: ${{ github.event.inputs.environment == 'prod' }}
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
          
      - name: Print environment variables
        run: |
          make setup
          make testp
          make lint
          make coverage
          
