name: Deploy Application

on:
#  push:
 #   branches:
  #    - main
      
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

# ✅ Global environment variables 
env:
  REGION: us-east-1
  APP_NAME: myapp
  

jobs:
  build:
    if: ${{ github.event.inputs.environment == 'prod' }}
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: test
   

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
          
      - name: Print environment variables
        run: |
          echo "App: $APP_NAME ${{ secrets.REMOTE_HOST }}"
          echo "Region: $REGION"
          echo "Build Dir: $BUILD_DIR"
  
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: "madanmadhur260@gmail.com"
          password: ${{ secrets.GMAIL1 }}
          subject: "GitHub Action Notification"
          to: "madhur9492@gmail.com"
          from: "madanmadhur260@gmail.com"
          body: |
            Workflow completed: ${{ github.workflow }}
            Status: "Success"
        
          
