name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build-and-push:
    runs-on: self-hosted
    container:
      image: gcr.io/kaniko-project/executor:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Docker credentials
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"${DOCKER_USERNAME}\",\"password\":\"${DOCKER_PASSWORD}\"}}}" > /kaniko/.docker/config.json
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image using Kaniko
        run: |
          /kaniko/executor \
            --context ${{ github.workspace }} \
            --dockerfile ${{ github.workspace }}/Dockerfile \
            --destination madhhur168/myapp:latest \
            --skip-tls-verify
